apiVersion: v1
name: ack-mq-controller
description: A Helm chart for the ACK service controller for mq
version: v0.0.5
appVersion: v0.0.5
home: https://github.com/aws-controllers-k8s/mq-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/mq-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: mq Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/mq-maintainer
keywords:
  - aws
  - kubernetes
  - mq
